name: Binary Testor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.x

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Binary Testor
        run: ruby engine.rb
