name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update Changelog
        run: |
          echo "## [${{ github.sha }}]" >> CHANGELOG.md
          git log --pretty=format:"- %s" ${{ github.sha }} >> CHANGELOG.md

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update Changelog for commit ${{ github.sha }}"
          git push
